# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: thomas.thomas@diamond.ac.uk
author_name: Thomas Thomas
component_owner: group:default/sscc
description: Electron Microscope monitoring system using prometheus
distribution_name: cryoem-monitor
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: cryoem-monitor
pypi: false
repo_name: cryoem-monitor
type_checker: mypy
