apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cryoem-monitor
  title: cryoem-monitor
  description: Electron Microscope monitoring system using prometheus
spec:
  type: documentation
  lifecycle: experimental
  owner: group:default/sscc