apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cryoem-monitor
  title: cryoem-monitor
  description: Electron Microscope monitoring system using prometheus
  annotations:
    github.com/project-slug: DiamondLightSource/cryoem-monitor
  tags:
    - python
    - cryoem
spec:
  type: service
  lifecycle: production
  owner: group:data-analysis
